#pragma once

#define MAKE_UARTE_INSTANCE(N) nrfx_uarte_t{NRFX_CONCAT_2(NRF_UARTE, N), NRFX_CONCAT_3(NRFX_UARTE, N, _INST_IDX)}
#define MAKE_TIMER_INSTANCE(N) nrfx_timer_t{NRFX_CONCAT_2(NRF_TIMER, N), NRFX_CONCAT_3(NRFX_TIMER, N, _INST_IDX), NRF_TIMER_CC_CHANNEL_COUNT(N)}
#define MAKE_TWIM_INSTANCE(N) nrfx_twim_t{NRFX_CONCAT_2(NRF_TWIM, N), NRFX_CONCAT_3(NRFX_TWIM, N, _INST_IDX)}
#define MAKE_SPIM_INSTANCE(N)  nrfx_spim_t{NRFX_CONCAT_2(NRF_SPIM, N), NRFX_CONCAT_3(NRFX_SPIM, N, _INST_IDX)}