#pragma once

#define DEBUG_NRF_USER 1

#define NRFX_SYSTICK_ENABLED 0

#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 0

#define NRF_CLOCK_ENABLED NRFX_CLOCK_ENABLED
#define CLOCK_CONFIG_LF_SRC NRFX_CLOCK_CONFIG_LF_SRC

#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER0_ENABLED 1

#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 1